alex_platform_home:
    path: /{page}
    defaults:
        _controller: AlexPlatformBundle:Advert:index
        page: 1
    requirements:
        page: \d*

alex_platform_view:
    path: /advert/{id}
    defaults:
        _controller: AlexPlatformBundle:Advert:view
    requirements:
        id: \d+

alex_platform_add:
    path: /add
    defaults:
        _controller: AlexPlatformBundle:Advert:add

alex_platform_edit:
    path: /edit/{id}
    defaults:
        _controller: AlexPlatformBundle:Advert:edit
    requirements:
        id: \d+

alex_platform_delete:
    path: /delete/{id}
    defaults:
        _controller: AlexPlatformBundle:Advert:delete
    requirements:
        id: \d+