services:
    alex_platform.antispam:
        class: Alex\PlatformBundle\Antispam\AlexAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50

#    alex_platform.example:
#        class: Alex\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

#parameters:



